### PR TITLE
refactor: remove require-all and do the imports explicitly

### PR DESCRIPTION
**Pull request by inigomarquinez**
## Description

Refactor the code to get rid of the `require-all` dependency. This has been done for 2 reasons:

1. From an arquitectural point of view, it's better to import explicitly rather than implicitly.
2. When using this module in a server component in a Nextjs app, the app crashes due to the require-all dependency.

Apart from this, I've taken advantage to improve the GitHub actions by pinning dependencies and using harden runner.

## Related Issue

When using this module in a server component in a Nextjs app, the app crashes due to the require-all dependency.

## Motivation and Context

When using this module in a server component in a Nextjs app, the app crashes due to the require-all dependency.

## How Has This Been Tested?

It's just a code refactor. All the existing tests pass.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code refactor

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM! I believe that this change is semver patch, not even minor

**Comment by UlisesGascon** [comment]
If nobody opposite to this change, I will suggest to merge it tomorrow morning and do a release :+1:

**Comment by inigomarquinez** [comment]
> LGTM! I believe that this change is semver patch, not even minor

Agree :)

**Review by nanotower — APPROVED** [review]
👍🏻

**Comment by inigomarquinez** [comment]
As there are no objections, I'll merge it and create a new release.

**Pull request merged**
